### PR TITLE
Add `hideAllToasts()` func.

### PR DESCRIPTION
**Pull request by eli-symbolab**
Clears the queue and removes the active toast (if any).

### CODE REVIEW

**Comment by eli-symbolab** [comment]
This addresses issue #61.

**Comment by freeenergyua** [comment]
Can anyone merge this to master please?)

**Comment by freeenergyua** [comment]
please add it to master!)

**Comment by scalessec** [comment]
Merged, thanks.

**Comment by scalessec** [comment]
Actually, I just realized this won't work if there are > 1 active toasts in a view. It's merged in `master` but I can't tag until this is fixed.

**Comment by eli-symbolab** [comment]
Whoops! Yep, if queuing is off and multiple toasts have been shown this won't close any except the last one.

**Pull request merged**
