### PR TITLE
Add carthage support

### PR DESCRIPTION
**Pull request by SandroMachado**
This PR adds `carthage` support to `Toast-Swift`.

### CODE REVIEW

**Comment by scalessec** [comment]
Awesome, thanks for this!

**Comment by SandroMachado** [comment]
@scalessec anyETA for the next release? :)

**Comment by scalessec** [comment]
@SandroMachado  I'll shoot for this weekend, but potentially this evening. I'd like to update the readme to note this change, but I'm not very familiar with Carthage yet. Is this all that needs to be done for people using Carthage?

Add this to your Cartfile:
`github "scalessec/Toast-Swift"`

And then run `carthage update`?

**Comment by SandroMachado** [comment]
It is required to specify a branch or a version. I created this [PR](https://github.com/scalessec/Toast-Swift/pull/17) with the `readme` updated with the instructions.

**Comment by scalessec** [comment]
Released `1.2.0`. Thanks!

**Pull request merged**
