### PR TITLE
Updated project for Xcode 10.2 & Swift 5

### PR DESCRIPTION
**Pull request by ppeelen**
I've solved the warnings that are presented in Xcode 10.2 and upgraded the projects settings to Swift 5.

Also referenced in issue https://github.com/scalessec/Toast-Swift/issues/137

### CODE REVIEW

**Comment by SamHFrancis** [comment]
This looks good, hopefully we can get this merged soon and release a new version. Though there is one more thing to do: update the Swift version in `Toast-Swift.podspec` to 5.0.

```ruby
s.swift_version = '5.0'
```

**Comment by scalessec** [comment]
Sorry for the delay on this. I'll review this PR and make sure a new pod is published in the next day or two. Thanks for your patience.

**Comment by scalessec** [comment]
Looks great, thanks!

**Comment by ppeelen** [comment]
Sorry for the late reply. Great work and thanks for merging it!

**Pull request merged**
